---
configure_dotfiles: false
configure_terminal: false

homebrew_installed_packages:
  - github/gh/gh
  - go
  - httpie
  - sqlite
  - nmap
  # - node
  # - nvm
  # - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - wget

homebrew_cask_apps:
  - transmit