---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
sudoers_custom_config: ''
# Example:
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - cowsay
  - github/gh/gh
  - git
  - go
  - httpie
  - iperf3
  - jbang
  - jq
  - mas
  - nmap
  - openssl
  - pandoc
  - pipx
  - pspg
  - pyenv
  - readline
  - ripgrep
  - shellcheck
  - sqlite
  - ssh-copy-id
  - starship
  - telnet
  - tree
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - a-better-finder-rename
  - alfred
  - bartender
  - dash
  - discord
  - docker
  - expressvpn
  - firefox
  - google-chrome
  - iina
  - intellij-idea
  - istat-menus
  - iterm2
  - maccy
  - menuwhere
  - microsoft-teams
  - mimestream
  - multipass
  - notion
  - paletro
  - parallels
  - pycharm
  - slack
  - soulver
  - spotify
  - sublime-merge
  - sublime-text
  - todoist
  - transmit
  - visual-studio-code
  - webstorm

# hazel
# iterm
# onedrive
# postgress.app
# synology drive client
# synology assistant
# whatsapp


# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1568262835, name: "Super Agent" }
  - { id: 1365531024, name: "1Blocker" }
  - { id: 497799835, name: "Xcode" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1469995354, name: "Broadcasts" }
  - { id: 1474335294, name: "GoodLinks" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 408981434, name: "iMovie" }
  - { id: 568494494, name: "Pocket" }
  - { id: 419330170, name: "Moom" }
  - { id: 409201541, name: "Pages" }
  - { id: 1529448980, name: "Reeder" }
  - { id: 1518425043, name: "Boop" }
  - { id: 409203825, name: "Numbers" }
  - { id: 1475387142, name: "Tailscale" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
